### ISSUE TITLE
The SVAMapView can't run on Android Marshmallow

### ISSUE THREAD

**Issue by BenjaminChoou** [jiahuanyu/SVGMapView#5]
The SVAMapView can't run on Android Marshmallow.
It always throws exceptions.
I hope you can fix these problems or just tell me what causes them.
Thank you.
As followed,
05-21 03:47:48.198 2358-2859/com.jiahuan.svgmapview.sample E/AndroidRuntime: FATAL EXCEPTION: Thread-105
                                                                             Process: com.jiahuan.svgmapview.sample, PID: 2358
                                                                             java.lang.ExceptionInInitializerError
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.doPath(SVGParser.java:363)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.access$1000(SVGParser.java:47)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser$SVGHandler.startElement(SVGParser.java:1747)
                                                                                 at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
                                                                                 at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
                                                                                 at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
                                                                                 at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.parse(SVGParser.java:91)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGBuilder.build(SVGBuilder.java:214)
                                                                                 at com.jiahuan.svgmapview.core.componet.MapMainView$2.run(MapMainView.java:384)
                                                                              Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field value in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-libart.jar)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.ParserHelper.<clinit>(ParserHelper.java:27)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.doPath(SVGParser.java:363) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.access$1000(SVGParser.java:47) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser$SVGHandler.startElement(SVGParser.java:1747) 
                                                                                 at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143) 
                                                                                 at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method) 
                                                                                 at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513) 
                                                                                 at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474) 
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316) 
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.parse(SVGParser.java:91) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGBuilder.build(SVGBuilder.java:214) 
                                                                                 at com.jiahuan.svgmapview.core.componet.MapMainView$2.run(MapMainView.java:384) 
                                                                              Caused by: java.lang.NoSuchFieldException: No field value in class Ljava/lang/String; (declaration of 'java.lang.String' appears in /system/framework/core-libart.jar)
                                                                                 at java.lang.Class.getDeclaredField(Native Method)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.ParserHelper.<clinit>(ParserHelper.java:24)
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.doPath(SVGParser.java:363) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.access$1000(SVGParser.java:47) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser$SVGHandler.startElement(SVGParser.java:1747) 
                                                                                 at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143) 
                                                                                 at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method) 
                                                                                 at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513) 
                                                                                 at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474) 
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316) 
                                                                                 at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGParser.parse(SVGParser.java:91) 
                                                                                 at com.jiahuan.svgmapview.core.helper.map.SVGBuilder.build(SVGBuilder.java:214) 
                                                                                 at com.jiahuan.svgmapview.core.componet.MapMainView$2.run(MapMainView.java:384)

**Comment by jiahuanyu** [comment]
I think u should try to change another method to get the char array from the origin string resource. see the constructor of ParseHelper.java.

``` java
try {
    this.s = (char[]) STRING_CHARS.get(str);
} catch (Exception e) {
    throw new RuntimeException(e);
}
```

``` java
try {
   STRING_CHARS = String.class.getDeclaredField("value");
    STRING_CHARS.setAccessible(true);
} catch (Exception e) {
    throw new RuntimeException(e);
}
```

reflection is used here may cause the exception.

**Comment by MedetZhakupov** [comment]
Just change the following line of code
`this.s = (char[]) STRING_CHARS.get(str);`
with 
`this.s = str.toCharArray();`

**Comment by BenjaminChoou** [comment]
Thank u!
According to the way you offer, I solved this problem.
It's really important for me to develop an indoor maps APP.Thanks again for helping me fix it.
